---
version: "2"
services:
  app:
    build: .
    environment:
      DBHOST: db:3306
      DATABASE: writedownhere
      DBUSER: writedownhere
      DBPASSWORD: writedownhere
    ports:
      - 8080:80
  db:
    image: mariadb:10.2
    environment:
      MYSQL_ROOT_PASSWORD: writedownhere
      MYSQL_DATABASE: writedownhere
      MYSQL_USER: writedownhere
      MYSQL_PASSWORD: writedownhere
    restart: always
    volumes:
      - ./sql/fixtures.sql:/docker-entrypoint-initdb.d/fixtures.sql:ro
      - mariadb:/var/lib/mysql
volumes:
  mariadb: {}
...
